FROM debian:stable-slim

ARG USE_MIRROR=1

RUN if [ ${USE_MIRROR} ]; then sed -i "s|http://deb.debian.org/debian|http://mirror.sjtu.edu.cn/debian|g" /etc/apt/sources.list ; fi && \
    apt-get update && \
    apt-get install --no-install-recommends --yes iproute2 openfortivpn iptables && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /usr/bin/entrypoint.sh

RUN chmod 755 /usr/bin/entrypoint.sh

ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]
CMD [ "openfortivpn" ]