FROM nadoo/glider:v0.15.3

ARG USE_MIRROR=1

USER root

RUN if [ ${USE_MIRROR} ]; then sed -i 's/dl-cdn.alpinelinux.org/mirrors.sjtug.sjtu.edu.cn/g' /etc/apk/repositories ; fi && \
    apk add --no-cache tzdata

USER glider